### ISSUE TITLE
"Strange" rectangular boxes in VR when using Pimax XR (Assetto Corsa Competizione, Automobilista 2)

### ISSUE THREAD

**Issue by JaZa1337** [mbucchia/Pimax-OpenXR#61] opened 2023-07-22 09:48 UTC
**Describe the bug**

Hello, 

whenever I play Assetto Corsa Competizione or Automobilista 2 with PimaxXR instead of SteamVR, there are one or two rectangular areas visible in VR. These are not visible with Steam VR. It does not happen in other games. Just the two mentioned above. I could not make a screenshot which shows my real VR view. So I created one with Paint to replicate what I´am seeing (second screenshot).

Greetings 

**Environment**
OpenXR Toolkit v1.3.2
PimaxXR v0.4.0
piTool V1.0.1.284
Pimax 5k Super, Firmware V2.1.255.273
Windows 10 Pro 22h2 64bit 
MSI RTX 4090 Suprim X
Assetto Corsa Competizione V1.9.5
Automobilista 2 V1.4.8.1 2305

**To Reproduce**

_Steps to reproduce the behavior:_

1. Use PimaxXR instead of Steam VR
2. Play either ACC or AMS2
3. Rectangular box(es) are shown

**Expected behavior**

_A clear and concise description of what you expected to happen._
View is the same as in Steam VR

![normal](https://github.com/mbucchia/Pimax-OpenXR/assets/140242340/68df233a-5d12-424f-aaf5-dd209175de48)
![vr](https://github.com/mbucchia/Pimax-OpenXR/assets/140242340/69f0e55e-f3ca-46c4-8fb4-48f1d6f5f8fc)
[pimax-openxr.log](https://github.com/mbucchia/Pimax-OpenXR/files/12136074/pimax-openxr.log)

**Comment by mbucchia** [comment] 2023-07-22 15:35
Pitool 284 is very old, have you tried with newer stuff like Pimax Client 1.13?

**Comment by JaZa1337** [comment] 2023-07-23 12:57
Thanks for your reply. I just tried it with  Pimax Client 1.13, unfortunately with the same result. One "box" shown in ACC and two "boxes" shown in Automobilista. It seems like the "boxes" are the area, where the HUD is rendered.

**Comment by Hummtaro** [comment] 2023-08-03 02:01
Dirt Rally 2.0 is affected too, but luckily the two boxes are much less intrusive, just a slight red tint with some small border.
Using latest OpenComposite and Pimax Client 1.13.02.01.
It looks more like #40

**Comment by JaZa1337** [comment] 2023-08-03 08:21
Interesting. Do you have the boxes also, if you use Steam VR? For me, they are only visible when using Open Composite + Pimax XR. For me, it also looks more like the screenshot you linked. Mine is overexaggerated, and poorly done with Paint :) But still, the box(es) are visible and disturbing. I wonder why it works with Assetto Corsa but not with Dirt Rally, ACC and AMS2. Maybe it has something to do with the game engine.

**Comment by JaZa1337** [comment] 2023-08-03 08:25
I also disabled all overlays in the Open XR Toolkit. Sadly it did not help.

**Comment by mbucchia** [comment] 2023-08-03 08:27
PimaxXR has a "Show mirror window" option, can you try it and see if you can capture an image of the phenomenon there?

**Comment by JaZa1337** [comment] 2023-08-03 09:52
Hi mbucchia,
I just tried it. You can see the outlines of the boxes in the screenshot. In my headset, these boxes are about 95% transparent and a slightly brighter color than the rest of the screen.
Greetings
![Boxes](https://github.com/mbucchia/Pimax-OpenXR/assets/140242340/d7cce852-e8be-4ec8-a22a-1e85c0d8066d)

**Comment by mbucchia** [comment] 2023-08-03 15:36
Thanks. At first glance this looks like the edges of quad layers submitted by the application. I don't do anything to those, just pass them to Pimax software for composition. So it looks like a Pimax bug, similar to the one we had with OpenXR Toolkit in the past. 
Any chance you could try Pimax Client 1.10?

**Comment by Hummtaro** [comment] 2023-08-03 16:58
![Screenshot 2023-08-03 182647](https://github.com/mbucchia/Pimax-OpenXR/assets/4927294/dd08111c-3709-45a8-b92a-f7f54f6b1933)
![IMG_20230803_182913_NR](https://github.com/mbucchia/Pimax-OpenXR/assets/4927294/cf45b330-a09a-4415-8fdf-a3144204684a)

It's the same here, in the mirror window you can only see the edges, while trough the lenes the boxes are like 5% opaque.

Those two boxes are most likely projection layers to show the hud and menu. And the problem could be that the post-processing is applied not only on the whole screen but additionally also in the composition of those boxes. Or something like that.

I already tried the Dirt Rally 2.0 / OpenComposite / PimaxXR combination about a year ago, back when #40 was still open and it was already the same.

And i had exact the same, years ago when i tried to play the old Oculus-exclusive Dirt Rally 1 via Pitool.
While it worked fine without those boxes via Revive in SteamVR.
So it's probably not a bug in OpenXR or OpenComposite since both weren't involved then..

**Comment by mbucchia** [comment] 2023-08-03 17:52
Thanks for the details.

It works fine with SteamVR  because SteamVR does its own composition of quad layers (2D menus, HUDs), bypassing the bogus Pimax composition. 

However PimaxXR (and I suspect Oculus mode emulation in Pitool) do not do that, and instead they rely on the quad layer composition in Pimax software, which had been crippled with bugs.

I don't think there is much I can do here. This is an issue Pimax needs to fix. I will try to write a bug report to them.

**Comment by Hummtaro** [comment] 2023-08-03 19:23
Another point: When starting the race, the screen is black and then fades in.
But via OpenComposite & PimaxXR, not the whole screen is black but only one of those boxes.
So maybe one of those boxes is meant to cover the whole view..
Or this fading is done via post processing and post-processing is applied only to the boxes instead of the screen for some reason..

Yeah, i'm fine with using SteamVR but it would be nice if they would fix this someday.. :-)

**Comment by mbucchia** [comment] 2023-09-10 21:49
Closing since these are Pimax issues I cannot do anything about.

**Closed by mbucchia** 2023-09-10 21:49 UTC
Labels: bug
