### ISSUE TITLE
Everslaught, index joystick drift

### ISSUE THREAD

**Issue by shebang79** [mbucchia/Pimax-OpenXR#20] opened 2022-08-02 09:49 UTC
Hi!

I quickly tested this out, the game seems to load up and play just fine, but the index knuckles are getting joystick drift, movement sort of slowly "lingers" in whatever direction I last moved in, and to come to a stop I'd have to very lightly press the opposite direction.

**Comment by mbucchia** [comment] 2022-08-02 15:54
What version did you try? I'm not seeing this issue in 0.2.4 with my Index controller.

**Comment by shebang79** [comment] 2022-08-02 18:42
Hmm, yeah I'm using 0.2.4. 

It doesn't happen with SteamVR, just this. Makes me think my knuckles probably have a bit of drift, but maybe SteamVR has a larger deadzone or something? My knuckles have some miles on them, after all.

**Comment by mbucchia** [comment] 2022-08-02 18:45
Makes sense, there is no dead zone implemented. Looks like I need to add it.

**Comment by shebang79** [comment] 2022-08-02 19:15
Ah, yeah. Excellent, thanks my friend!

In the meantime, I'll play with my Swords -- always have a backup, right? 🧠👈

**Comment by mbucchia** [comment] 2022-08-02 19:27
Do the Sword work with PimaxXR? I have not found anybody to try it for me. If you can, can you capture some info for me: https://github.com/mbucchia/Pimax-OpenXR/wiki/Capturing-debug-traces. This will help me understand how the Swords are advertised by the system, and whether the implementation is correct.

Thanks.

**Comment by shebang79** [comment] 2022-08-02 19:31
I'd be happy to try! I've got a few Meataverse chores I have to run, but I'll give them a go later today and post the results.

**Comment by mbucchia** [comment] 2022-08-03 05:47
When you have a chance, can you also let me know if this everslaught games works well with PimaxXR? It's native OpenXR and does not need OpenComposite? Does not need PP? I would like to add it to the official Compatibility list on the wiki.
Thanks.

**Comment by mbucchia** [comment] 2022-08-03 16:29
Thank you, this is very helpful. I think I see the trackpad issue and can fix that.

No idea about your other issue, it doesn't make too much sense. Perhaps another trace would help.

**Comment by mbucchia** [comment] 2022-08-20 21:35
Configurable deadzone is added in 6a20a8d7918e165db299f6752e75a09e74178f3b.

Looking at the touchpad issue next.

**Comment by mbucchia** [comment] 2022-10-01 09:25
So I fixed a lot of things with motion controllers in 0.2.8, and I believe it should address the issue with Sword (the "holding" of last input). Dunno about the issue with Uberlaufer but worth a try if you have some time.

Thanks.

**Comment by mbucchia** [comment] 2022-11-06 23:39
Known and reproducible issues have been resolved for >1 month. Closing.

**Closed by mbucchia** 2022-11-06 23:39 UTC
