### ISSUE TITLE
Error during Vulkan initialization

### ISSUE THREAD

**Issue by SEt-t** [mbucchia/Pimax-OpenXR#6] opened 2022-06-12 02:36 UTC
VkDeviceCreateInfo::pEnabledFeatures can be NULL, now it's crashing.
Solution is obvious: copy the pointer, not the data.

Also, XR_KHR_vulkan_enable does work for me, just need to enumerate returned device extensions a bit more carefully.

**Comment by mbucchia** [comment] 2022-06-12 02:55
Thanks! This code is copy pasted from the Khronos sample(!) and I did not review it carefully. 

I expect `XR_KHR_vulkan_enable` to work OK but the issue is that it does not let the runtime pass extended structures to device creation, so we cannot enable timeline semaphore properly. On my NVidia card this results in a validation layer error, but still works as well.

If you want to make sure it's portable, then make sure to enable timeline semaphore in your code when creating the device.

https://github.com/mbucchia/Pimax-OpenXR/blob/33a75865cb1be090fe5f70c6f4a6b794d262b26c/pimax-openxr/runtime.cpp#L1164

**Comment by mbucchia** [comment] 2022-06-12 02:57
Also I'd be curious at some point to get an ETL trace from your app. Just to see the calling patterns etc for curiosity.  (And if that's ok)OK.

So far I only tested Vulkan support with HelloXR and Unity 2021.

**Comment by SEt-t** [comment] 2022-06-12 03:05
Enabling timelineSemaphore is exactly what I meant by "a bit more carefully".

Currently we are at the stage of total rewrite, so any traces are meaningless. Maybe in a month or so... In general, API calls are very basic with heavy compute in few shaders.

**Comment by mbucchia** [comment] 2022-06-12 03:34
Should be fixed in 71a7c23889a4004f7748de8a4bc423b83d8e3016. Thank you very much for the report!

**Closed by mbucchia** 2022-06-12 03:34 UTC
