### ISSUE TITLE
Pimax 8KX in DCS - Everything jitters/lags until I stop

### ISSUE THREAD

**Issue by adrian-fazaeli** [mbucchia/Pimax-OpenXR#54] opened 2023-03-26 14:34 UTC
Hi, 
In the DCS when I move my head, everything jitters/lags until I stop , I have this issue just in Release 0.3.2 
In Release 0.2.8 everything working perfectly

**Comment by mbucchia** [comment] 2023-03-26 18:08
Duplicate of #53

**Closed by mbucchia** 2023-03-26 18:08 UTC
Labels: bug
