### ISSUE TITLE
0.1.4, DCS, crazy position jitter in menu

### ISSUE THREAD

**Issue by ags313** [mbucchia/Pimax-OpenXR#4] opened 2022-06-12 00:08 UTC
Hi, I'm on a Pimax8KX, just downloaded 0.1.4, and I am observing crazy tracking in the menu - for example, on the multiplayer server selection screen, where the UI thread of DCS seems blocked to process updates.
Once in flight, it looks stable in short tests.

Pimax OpenVR log says:
```
2022-06-12 00:52:26 +0100: PimaxXR - v0.1.4
2022-06-12 00:52:26 +0100: PVR: 1.23.1
2022-06-12 00:52:26 +0100: Application: OpenComposite_DCS; Engine: 
2022-06-12 00:52:26 +0100: Detected OpenComposite
2022-06-12 00:52:26 +0100: Requested extension: XR_KHR_D3D11_enable
2022-06-12 00:52:26 +0100: Requested extension: XR_KHR_D3D12_enable
2022-06-12 00:52:26 +0100: Requested extension: XR_KHR_vulkan_enable
2022-06-12 00:52:26 +0100: Requested extension: XR_KHR_visibility_mask
2022-06-12 00:52:26 +0100: Using Vulkan on adapter: NVIDIA GeForce RTX 3090
2022-06-12 00:52:30 +0100: Using Direct3D 11 on adapter: NVIDIA GeForce RTX 3090
```
Trace added [PimaxXR.zip](https://github.com/mbucchia/Pimax-OpenXR/files/8884918/PimaxXR.zip)

**Comment by mbucchia** [comment] 2022-06-12 00:38
Thanks. Is this a regression from 0.1.2? I think the cause is likely the "pose prediction timestamp" change, though it had no problems for me. Do you have lighthouse or just 9-axis setup?

**Comment by ags313** [comment] 2022-06-12 00:44
I never had it before, but I started with 0.1.0.
I use 2 lighthouses.

**Comment by Negajoule** [comment] 2022-06-12 00:48
I have a similar issue and I use 2 lighthouses also

**Comment by mbucchia** [comment] 2022-06-12 00:55
I will investigate.  It's working perfectly for me :|

**Comment by ags313** [comment] 2022-06-12 01:10
If I try to stabilise (lean against a chair), it starts slower. A multiplier too aggressive/decay not kicking in? (wild guesses)

**Comment by mbucchia** [comment] 2022-06-12 01:14
I don't do any transforms or things like that.

I don't have lighthouse so I have only tested 9 Axis.
Do you have any pure OpenXR app (not OpenComposite) to test with? If not can you try the StereoKitCTest app from https://mbucchia.github.io/OpenXR-Toolkit/download/TestApps.zip?

**Comment by Negajoule** [comment] 2022-06-12 01:46
> I don't do any transforms or things like that.
> 
> I don't have lighthouse so I have only tested 9 Axis. Do you have any pure OpenXR app (not OpenComposite) to test with? If not can you try the StereoKitCTest app from https://mbucchia.github.io/OpenXR-Toolkit/download/TestApps.zip?

I tried the StereoKitCTest and it loaded and the image was stable (though the mouse was not usable in the VR world and I do not have controllers)

**Comment by mbucchia** [comment] 2022-06-12 01:50
The likely cause is 3621c9c96606d708f25d4d4ef77842235a353193, which is a change that I don't understand but seemed necessary for OpenComposite. I think they are initializing their Direct3D device with flags incompatible with the new Pimax SDK... I might not be able to do anything about this.

**Comment by mbucchia** [comment] 2022-06-12 02:13
Can you try to drop this `pimax-openxr.dll` file into `C:\Program Files\PimaxXR`?
[pimax-openxr.zip](https://github.com/mbucchia/Pimax-OpenXR/files/8885057/pimax-openxr.zip)

**Comment by SEt-t** [comment] 2022-06-12 02:22
Maybe related info: I also had issue with OpenComposite + Pimax, but in different place (without OpenXR at all). Call to ovr_CommitTextureSwapChain (into Pimax ovr layer) was returning error code and its check was failing everything.

Solution, as strange as it sounds, was to still to call the function but not to check the result.

**Comment by mbucchia** [comment] 2022-06-12 02:25
pvr_beginFrame just plain segfaults upon first call but only with OpenComposite... looks like skipping the first call works (this is the dll I posted above). I hope this will do.

**Comment by Negajoule** [comment] 2022-06-12 02:27
> Can you try to drop this `pimax-openxr.dll` file into `C:\Program Files\PimaxXR`? [pimax-openxr.zip](https://github.com/mbucchia/Pimax-OpenXR/files/8885057/pimax-openxr.zip)

I will test it asap

**Comment by Negajoule** [comment] 2022-06-12 03:24
> Can you try to drop this pimax-openxr.dll file into C:\Program Files\PimaxXR? [pimax-openxr.zip]

Tested and that corrected the issue of the screen spinning. I was able to load in DCS and fly normally. 
However, on exiting DCS I received an error message. I could not screenshot it but I will run again and try to get a log and screenshot of the error

**Comment by Negajoule** [comment] 2022-06-12 03:34
Screenshot of error and log
2022-06-11 22:32:02 -0500: PimaxXR - v0.1.4
2022-06-11 22:32:02 -0500: PVR: 1.23.1
2022-06-11 22:32:02 -0500: Hidden area mesh is not enabled
2022-06-11 22:32:02 -0500: Application: OpenComposite_DCS; Engine: 
2022-06-11 22:32:02 -0500: Requested extension: XR_KHR_D3D11_enable
2022-06-11 22:32:02 -0500: Requested extension: XR_KHR_D3D12_enable
2022-06-11 22:32:02 -0500: Requested extension: XR_KHR_vulkan_enable
2022-06-11 22:32:02 -0500: Using Vulkan on adapter: NVIDIA GeForce RTX 3080 Ti
2022-06-11 22:32:07 -0500: Using Direct3D 11 on adapter: NVIDIA GeForce RTX 3080 Ti
2022-06-11 22:33:50 -0500: xrBeginFrame: pvrResult failure [ffffffff]
    Origin: pvr_beginFrame(m_pvrSession, m_currentFrameIndex)
    Source: D:\XRAE\Stuff\Pimax-OpenXR\pimax-openxr\runtime.cpp:233
![Screenshot 2022-06-11 223713](https://user-images.githubusercontent.com/99090002/173213239-6199f094-c82b-4310-94e6-c04e69005ef5.png)
3

**Comment by mbucchia** [comment] 2022-06-12 03:35
First issue should be fixed in 95be4667dcddfc8fe92b002891574ae3c56ad495.

**Comment by mbucchia** [comment] 2022-06-12 03:37
Can you try this build now?
[PimaxXR-0.1.5b.zip](https://github.com/mbucchia/Pimax-OpenXR/files/8885143/PimaxXR-0.1.5b.zip)

NOTE: This one is a full installer, not just the DLL.

**Comment by Negajoule** [comment] 2022-06-12 03:47
> Can you try this build now? [PimaxXR-0.1.5b.zip](https://github.com/mbucchia/Pimax-OpenXR/files/8885143/PimaxXR-0.1.5b.zip)
> 
> NOTE: This one is a full installer, not just the DLL.

That version seems to have corrected the issue and no error was thrown on DCS exit

Thanks

**Comment by mbucchia** [comment] 2022-06-12 15:05
Fixed the remaining issue in d48464c2d8df2faded3958a039a17619f17b291e. Releasing 0.1.6 in a few minutes,

Thank you for the help!

**Closed by mbucchia** 2022-06-12 15:05 UTC

**Comment by ags313** [comment] 2022-06-12 16:22
Thanks, will give it a try!

**Comment by ags313** [comment] 2022-06-12 21:16
Yes, all works. Thank you for the fix!
