### ISSUE TITLE
DCS  screen rapidly shakes and game is unusable

### ISSUE THREAD

**Issue by Negajoule** [mbucchia/Pimax-OpenXR#5] opened 2022-06-12 00:23 UTC
In DCS, as soon as the menu screen loads (within seconds) the image begins jittering and shaking exponentially faster to the point that it looks like it is in a blender after 7-10 seconds and I have to hard kill DCS.

Have attempted with multiple versions of OpenComposite (past 2 versions and current) and with Recenter enabled and disabled in PimaxXR Control Center

LOG follows:
2022-06-11 19:18:20 -0500: PimaxXR - v0.1.4
2022-06-11 19:18:20 -0500: PVR: 1.23.1
2022-06-11 19:18:20 -0500: Hidden area mesh is not enabled
2022-06-11 19:18:20 -0500: Application: OpenComposite_DCS; Engine: 
2022-06-11 19:18:20 -0500: Detected OpenComposite
2022-06-11 19:18:20 -0500: Requested extension: XR_KHR_D3D11_enable
2022-06-11 19:18:20 -0500: Using Direct3D 11 on adapter: NVIDIA GeForce RTX 3080 Ti

**Comment by mbucchia** [comment] 2022-06-12 00:36
Duplicate of #4.

**Closed by mbucchia** 2022-06-12 00:36 UTC
