### ISSUE TITLE
Recommended resolution problem causes crash on start

### ISSUE THREAD

**Issue by albertowd** [mbucchia/Pimax-OpenXR#48] opened 2023-01-29 21:20 UTC
**Describe the bug**

Using the latest PiTool version available 284, I cannot play DCS anymore with my Pimax4K headset. With OpenXR I can play without issues, but with PimaxXR the driver tries to use a ***HUGE RESOLUTION***. It`s recommendation is 106158x157726!!!
So the games crashes on start trying to allocate textures, I`m guessing that it cannot allocate enough VRAM as desired to create a game with such a resolution....

PiTools settings:
![image](https://user-images.githubusercontent.com/4700240/215355960-b6b4e7cd-eb24-48de-b122-8c76c7c830d8.png)

OpenXR settings:
![image](https://user-images.githubusercontent.com/4700240/215355967-cf104054-2b4d-41fc-92a0-7bea8db54010.png)

PimaxXR settings:
![image](https://user-images.githubusercontent.com/4700240/215355975-e1f3389f-bcff-4a42-aba0-af9f731d1c69.png)

DCS logs:
```
2023-01-29 21:01:28.397 INFO    VISUALIZER (Main): LAUNCH IN VR OpenVR: OpenVR : 
2023-01-29 21:01:28.399 INFO    GRAPHICSVISTA (Main): renderer: 'dx11backend.dll'
2023-01-29 21:01:28.479 INFO    DX11BACKEND (Main): DX11Renderer initialization (w:936 h:1391 fullscrn:0 vsync:0 adapter:0 monitor:0 shaderErrors:1)
2023-01-29 21:01:28.516 INFO    DX11BACKEND (Main): Driver Concurrent Creates - 1
2023-01-29 21:01:28.516 INFO    DX11BACKEND (Main): Driver Command Lists - 1
2023-01-29 21:01:28.521 INFO    DX11BACKEND (Main): NVIDIA API init OK
2023-01-29 21:01:28.521 INFO    DX11BACKEND (Main): NVIDIA Display Driver Version 52824.r528_10
2023-01-29 21:01:28.521 INFO    DX11BACKEND (Main): GPU count:1
2023-01-29 21:01:28.906 INFO    DX11BACKEND (Main): commonPool: 48-128, cbPool: 4-14
2023-01-29 21:01:28.906 INFO    DX11BACKEND (Main): samplerPool: 5-16
2023-01-29 21:01:28.906 INFO    METASHADER (Main): Init filesystem: C
2023-01-29 21:01:28.914 INFO    DX11BACKEND (Main): DX11ShaderBinaries::loadCache Bazar/shaders/fxo/fxo.zip
2023-01-29 21:01:31.072 INFO    DX11BACKEND (Main): DX11ShaderBinaries::loadCache done. Loaded 1864/1865.
2023-01-29 21:01:31.092 INFO    DX11BACKEND (Main): DX11ShaderBinaries::loadCache C:\Users\albertowd\Saved Games\DCS.openbeta\fxo
2023-01-29 21:01:31.121 INFO    DX11BACKEND (Main): DX11ShaderBinaries::loadCache done. Loaded 140/140.
2023-01-29 21:01:31.140 INFO    VISUALIZER (Main): SceneManager initialization
2023-01-29 21:01:31.141 ERROR   DX11BACKEND (Main): Failed assert `false && "failed to create texture"` at Projects\render\dx11backend_win8\Source\DX11TextureManager.cpp:710
2023-01-29 21:01:31.141 WARNING LOG (23580): 1 duplicate message(s) skipped.
2023-01-29 21:01:31.141 INFO    EDCORE (Main): try to write dump information
2023-01-29 21:01:31.143 INFO    EDCORE (Main): # -------------- 20230129-210131 --------------
2023-01-29 21:01:31.143 INFO    EDCORE (Main): DCS/2.8.2.35759 (x86_64; Windows NT 10.0.22621)
2023-01-29 21:01:31.143 INFO    EDCORE (Main): C:\Program Files\Eagle Dynamics\DCS World OpenBeta\bin\dx11backend.dll
2023-01-29 21:01:31.144 INFO    EDCORE (Main): # C0000005 ACCESS_VIOLATION at 00007FFAD8469EC2 00:00000000
2023-01-29 21:01:31.145 INFO    EDCORE (Main): SymInit: Symbol-SearchPath: '.;C:\Program Files\Eagle Dynamics\DCS World OpenBeta;C:\Program Files\Eagle Dynamics\DCS World OpenBeta\bin;C:\Windows;C:\Windows\system32;SRV*C:\websymbols*https://msdl.microsoft.com/download/symbols;', symOptions: 528, UserName: 'albertowd'
2023-01-29 21:01:31.145 INFO    EDCORE (Main): OS-Version: 10.0.22621 () 0x100-0x1
2023-01-29 21:01:31.261 INFO    EDCORE (Main): 0x0000000000009EC2 (dx11backend): RenderAPI::DX11Renderer::useTesselatorStage + 0x4DE2
2023-01-29 21:01:31.262 INFO    EDCORE (Main): 0x0000000000009BD2 (dx11backend): RenderAPI::DX11Renderer::useTesselatorStage + 0x4AF2
2023-01-29 21:01:31.262 INFO    EDCORE (Main): 0x0000000000010E82 (dx11backend): RenderAPI::DX11Renderer::createFrameBuffer + 0x82
2023-01-29 21:01:31.262 INFO    EDCORE (Main): 0x0000000000010D89 (dx11backend): RenderAPI::DX11Renderer::createFrameBuffer + 0x1D9
2023-01-29 21:01:31.262 INFO    EDCORE (Main): 0x000000000005E8A6 (Visualizer): Entity::deduceComponentTypeEnum<TransformComponent> + 0xDE6
2023-01-29 21:01:31.263 INFO    EDCORE (Main): 0x00000000000BDBD2 (Visualizer): HMD::setPlatformCompensation + 0x9782
2023-01-29 21:01:31.263 INFO    EDCORE (Main): 0x00000000000E6959 (Visualizer): ViewportCalcCamera + 0x4DB9
2023-01-29 21:01:31.263 INFO    EDCORE (Main): 0x00000000000E9761 (Visualizer): smSceneManager::CreateSceneManager + 0xE1
2023-01-29 21:01:31.263 INFO    EDCORE (Main): 0x0000000000848E3E (DCS): SW + 0x3DD2CE
2023-01-29 21:01:31.264 INFO    EDCORE (Main): 0x0000000000847526 (DCS): SW + 0x3DB9B6
2023-01-29 21:01:31.264 INFO    EDCORE (Main): 0x00000000022EE5AD (DCS): AmdPowerXpressRequestHighPerformance + 0xF8B5A9
2023-01-29 21:01:31.264 INFO    EDCORE (Main): 0x0000000000C14F72 (DCS): SW + 0x7A9402
2023-01-29 21:01:31.264 INFO    EDCORE (Main): 0x00000000000126BD (KERNEL32): BaseThreadInitThunk + 0x1D
2023-01-29 21:01:31.264 INFO    EDCORE (Main): 0x000000000005DFB8 (ntdll): RtlUserThreadStart + 0x28
2023-01-29 21:01:31.458 INFO    EDCORE (Main): Minidump created.
```

PimaxXR logs:
```
2023-01-29 18:01:20 -0300: PimaxXR - v0.3.0
2023-01-29 18:01:20 -0300: PVR: 1.23.1
2023-01-29 18:01:20 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-29 18:01:20 -0300: Detected OpenComposite
2023-01-29 18:01:20 -0300: Parallel projection is enabled
2023-01-29 18:01:20 -0300: Device is: Pimax 4K
2023-01-29 18:01:22 -0300: PVR: 1.23.1
2023-01-29 18:01:22 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-29 18:01:22 -0300: Detected OpenComposite
2023-01-29 18:01:22 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-29 18:01:22 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-29 18:01:22 -0300: Requested extension: XR_KHR_win32_convert_performance_counter_time
2023-01-29 18:01:22 -0300: Parallel projection is enabled
2023-01-29 18:01:22 -0300: Device is: Pimax 4K
2023-01-29 18:01:24 -0300: Recommended resolution: 106158x157726
2023-01-29 18:01:25 -0300: PimaxXR - v0.3.0
2023-01-29 18:01:25 -0300: PVR: 1.23.1
2023-01-29 18:01:25 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-29 18:01:25 -0300: Detected OpenComposite
2023-01-29 18:01:25 -0300: Parallel projection is enabled
2023-01-29 18:01:25 -0300: Device is: Pimax 4K
2023-01-29 18:01:26 -0300: PVR: 1.23.1
2023-01-29 18:01:26 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-29 18:01:26 -0300: Detected OpenComposite
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_D3D11_enable
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_D3D12_enable
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_vulkan_enable
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_opengl_enable
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-29 18:01:26 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-29 18:01:26 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-29 18:01:26 -0300: Requested extension: XR_KHR_win32_convert_performance_counter_time
2023-01-29 18:01:26 -0300: Parallel projection is enabled
2023-01-29 18:01:26 -0300: Device is: Pimax 4K
2023-01-29 18:01:28 -0300: Recommended resolution: 106158x157726
2023-01-29 18:01:28 -0300: Using D3D11 on adapter: NVIDIA GeForce RTX 3070 Ti
```

**Environment**

- _Application/Game and version_:   DCS 2.8 Open Beta
- _Version of Pitool or Pimax client_: 284

**To Reproduce**

_Steps to reproduce the behavior:_

1. Run OpenComposite Launcher or copy the dll into the `DCS\bin` folder
2. If installed the Launcher, open OpenComposite and select OpenXR
3. Open PimaxXR
4. Open the Game and enable VR settings
5. Games crashes on start

**Expected behavior**

The resolution should match*ish* 2556x1440 as the settings on the PiTool. The game crashes probably due to lack o VRAM used to create that size of resolution buffers....

**Comment by mbucchia** [comment] 2023-01-29 21:29
Can you try disabling Parallel Projection and see if the issue reproduces? The resolution that PimaxXR uses is the one advertised by Pitool, but when Parallel Projection is on, there is extra math, which might be the culprit here.

**Comment by albertowd** [comment] 2023-01-29 21:44
> Can you try disabling Parallel Projection and see if the issue reproduces? The resolution that PimaxXR uses is the one advertised by Pitool, but when Parallel Projection is on, there is extra math, which might be the culprit here.

Same problem:
![image](https://user-images.githubusercontent.com/4700240/215357212-205b8fd8-4f65-40d8-a1dd-2919abfff4d7.png)

Note: Pimax4K does not have a "Compatible with parallel projections" options as other Pimax headsets on the PiTools options panel, so I tryied do disable it through the OpenXR app, without success it seems :D

**Comment by mbucchia** [comment] 2023-01-29 21:51
What you call "the OpenXR app" is OpenXR Tools FOR WINDOWS MIXED REALITY, which isn't applicable here. None of it is applicable here, and those settings do nothing on any devices other than WMR (eg: G2).

It looks like your issue is really specific to Pimax 4K, and I don't really have a good way to investigate. Perhaps capture a trace from PimaxXR Control Center and send me that.

https://github.com/mbucchia/Pimax-OpenXR/wiki/Capturing-debug-traces

Thanks.

**Comment by albertowd** [comment] 2023-01-29 22:03
> What you call "the OpenXR app" is OpenXR Tools FOR WINDOWS MIXED REALITY, which isn't applicable here. None of it is applicable here, and those settings do nothing on any devices other than WMR (eg: G2).
> 
> It looks like your issue is really specific to Pimax 4K, and I don't really have a good way to investigate. Perhaps capture a trace from PimaxXR Control Center and send me that.
> 
> https://github.com/mbucchia/Pimax-OpenXR/wiki/Capturing-debug-traces
> 
> Thanks.

Sure, anything to help!

Btw, I`ve noticed my VRAM goes through the roof when starting the game....
![image](https://user-images.githubusercontent.com/4700240/215358045-6285ba56-252e-42e6-a0e6-3908e3f9e991.png)

My etl file:
[PimaxXR.zip](https://github.com/mbucchia/Pimax-OpenXR/files/10530983/PimaxXR.zip)

**Comment by mbucchia-msft** [comment] 2023-01-29 22:18
OK the trace is very helpful, and it 100% points to a bug in Pitool:

VendorId:1155 ProductId:33 Manufacturer:Pimax VR, Inc. ProductName:Pimax 4K SerialNumber:10071173003052 FirmwareMinor:0 FirmwareMajor:0 **ResolutionWidth:206932 ResolutionHeight:127296**

Pimax itself is telling us this crazy high base resolution. This is the call to Pimax's own function `pvr_getHmdInfo()`:

https://github.com/mbucchia/Pimax-OpenXR/blob/main/pimax-openxr/system.cpp#L75

This is a bug to report to Pimax. What I can try doing for now is when I detect ProductName == Pimax 4K, I will try ignoring the logic to get the resolution from Pitool, and instead hard-code the resolution. This will break things like Pitool Render Quality slider and HMD resolution however... Nothing I can do about this until Pimax fixes their bug.

**Comment by albertowd** [comment] 2023-01-29 22:27
Sure, I appreciate all the trouble to help me with this problem.
I`ll open a new issue on the OpenMR forum ASAP. Can I mention this issue here?
Meanwhile, if you want me to test some preview workarounds for PimaxXR I`m here for you <3
Thanks again!

**Comment by mbucchia** [comment] 2023-01-29 22:32
Please feel free to reference my message above, which shows the name of the PVR API and shows the strange values we observed.

**Comment by albertowd** [comment] 2023-01-29 22:53
Thanks, mentioned on: [OpenMR Feedback Topic](https://community.openmr.com/t/pitools-1-0-1-284-pvr-gethmdinfo-resolution-problem-on-pimax-4k/40333)

Any new builds you want to test, you can call me here or on any other platform ;)

**Comment by mbucchia** [comment] 2023-01-30 08:34
Commit c07c5cf22e2d8d4698a18ac325948c490fd86d4e fixes FOV calculation issues with Pimax 4K.

**Comment by mbucchia** [comment] 2023-01-30 09:25
@albertowd, could you give a try to this build: https://nightly.link/mbucchia/Pimax-OpenXR/actions/artifacts/532570558.zip

Thanks!

**Comment by albertowd** [comment] 2023-01-30 12:40
Tested! The build work as the 0.3.0 version with 58 degrees.
I`ve captured this trace too to help:
[PimaxXR.zip](https://github.com/mbucchia/Pimax-OpenXR/files/10535772/PimaxXR.zip)
The log:
```
2023-01-30 09:32:55 -0300: PimaxXR - v0.3.1
2023-01-30 09:32:55 -0300: PVR: 1.23.1
2023-01-30 09:32:55 -0300: Hidden area mesh is not enabled
2023-01-30 09:32:55 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-30 09:32:55 -0300: Device is: Pimax 4K
2023-01-30 09:32:57 -0300: PVR: 1.23.1
2023-01-30 09:32:57 -0300: Hidden area mesh is not enabled
2023-01-30 09:32:57 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-30 09:32:57 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-30 09:32:57 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-30 09:32:57 -0300: Requested extension: XR_KHR_win32_convert_performance_counter_time
2023-01-30 09:32:57 -0300: Device is: Pimax 4K
2023-01-30 09:32:59 -0300: Recommended resolution: 1386x1988
2023-01-30 09:33:00 -0300: PimaxXR - v0.3.1
2023-01-30 09:33:00 -0300: PVR: 1.23.1
2023-01-30 09:33:00 -0300: Hidden area mesh is not enabled
2023-01-30 09:33:00 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-30 09:33:00 -0300: Device is: Pimax 4K
2023-01-30 09:33:01 -0300: PVR: 1.23.1
2023-01-30 09:33:01 -0300: Hidden area mesh is not enabled
2023-01-30 09:33:01 -0300: Application: OpenComposite_DCS; Engine: 
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_D3D11_enable
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_D3D12_enable
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_vulkan_enable
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_opengl_enable
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-30 09:33:01 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-30 09:33:01 -0300: Requested extension: XR_EXT_hand_tracking
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_visibility_mask
2023-01-30 09:33:01 -0300: Requested extension: XR_KHR_win32_convert_performance_counter_time
2023-01-30 09:33:01 -0300: Device is: Pimax 4K
2023-01-30 09:33:03 -0300: Recommended resolution: 1386x1988
2023-01-30 09:33:03 -0300: Using D3D11 on adapter: NVIDIA GeForce RTX 3070 Ti
2023-01-30 09:33:08 -0300: Using D3D11 on adapter: NVIDIA GeForce RTX 3070 Ti

```

**Comment by albertowd** [comment] 2023-01-30 13:35
Actually, after some tests with OpenXR and SteamVR, the same image result is now being presented correctly, independent of the 58.3 degrees the PimaxXR says it should be.
Another thing to notice: the resolution is the same as the SteamVR says it should be on 100% resolution.
The fix definitively worked to restore the image I was having before this issue!
You can see the 0.3.0 version the image is narrower and lacks the image mask, I don't know if that's because the mask is rendered outside of the old FOV calculation or not rendered at all....

PimaxXR  0.3.1 on DCS screenshot:
![image](https://user-images.githubusercontent.com/4700240/215488511-0b4e12d6-464d-4673-987d-a6c9dd5c60f1.png)

Actual SteamVR on DCS screenshot:
![image](https://user-images.githubusercontent.com/4700240/215489060-36333cfb-e481-4a30-813c-509784155f59.png)

PimaxXR 0.3.0 on DCS screenshot:
![image](https://user-images.githubusercontent.com/4700240/215489934-3baf0772-1e8e-4d8a-a830-e9c792e4c90a.png)

Thanks for this fix, even if it's not definitive, really it helped me a lot!

**Comment by mbucchia** [comment] 2023-01-30 16:29
Cool so it looks good in the HMD but it is PimaxXR Control Center that shows the wrong number?

I thought I had fixed that too, will need to to double-check.

**Comment by albertowd** [comment] 2023-01-30 17:54
> Cool so it looks good in the HMD but it is PimaxXR Control Center that shows the wrong number?
> 
> I thought I had fixed that too, will need to to double-check.

Yep, event with the right image rendering, the interface still shows the wrong FOV value:
![image](https://user-images.githubusercontent.com/4700240/215555542-d6d37e7f-5fef-4ba0-bafd-3bedef0a1094.png)

**Comment by albertowd** [comment] 2023-01-30 18:00
As the Pimax 4K has 110 degrees of horizontal FOV, each eye should have +-55, so it could be right to calculate +-58 for each one with the HMD upscaling?

**Comment by SEt-t** [comment] 2023-01-31 15:21
> Commit [c07c5cf](https://github.com/mbucchia/Pimax-OpenXR/commit/c07c5cf22e2d8d4698a18ac325948c490fd86d4e) fixes FOV calculation issues with Pimax 4K.

That is just ugly. Why hardcode when you can get canting angle directly as angle between quaternions pvrEyeRenderInfo::HmdToEyePose.Orientation ?

**Comment by mbucchia** [comment] 2023-01-31 16:07
Please, provide a better change and I will approve the PR.

**Comment by mbucchia** [comment] 2023-03-18 03:00
The fix for this had been on for a while now. Closing.

**Closed by mbucchia** 2023-03-18 03:00 UTC
Labels: bug
